# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: captcha.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcaptcha.proto\"\x1e\n\x06Result\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"5\n\x0e\x43\x61ptchaRequest\x12\x0f\n\x07\x62g_path\x18\x01 \x01(\t\x12\x12\n\nfront_path\x18\x02 \x01(\t\"*\n\x0eResultResponse\x12\x18\n\x07results\x18\x01 \x03(\x0b\x32\x07.Result2I\n\x11\x43\x61ptchaProcessing\x12\x34\n\x0eProcessCaptcha\x12\x0f.CaptchaRequest\x1a\x0f.ResultResponse\"\x00\x42\nZ\x08/captchab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'captcha_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010/captcha'
  _globals['_RESULT']._serialized_start=17
  _globals['_RESULT']._serialized_end=47
  _globals['_CAPTCHAREQUEST']._serialized_start=49
  _globals['_CAPTCHAREQUEST']._serialized_end=102
  _globals['_RESULTRESPONSE']._serialized_start=104
  _globals['_RESULTRESPONSE']._serialized_end=146
  _globals['_CAPTCHAPROCESSING']._serialized_start=148
  _globals['_CAPTCHAPROCESSING']._serialized_end=221
# @@protoc_insertion_point(module_scope)
