# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import captcha_pb2 as captcha__pb2


class CaptchaProcessingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessCaptcha = channel.unary_unary(
                '/CaptchaProcessing/ProcessCaptcha',
                request_serializer=captcha__pb2.CaptchaRequest.SerializeToString,
                response_deserializer=captcha__pb2.ResultResponse.FromString,
                )


class CaptchaProcessingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessCaptcha(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CaptchaProcessingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessCaptcha': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessCaptcha,
                    request_deserializer=captcha__pb2.CaptchaRequest.FromString,
                    response_serializer=captcha__pb2.ResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CaptchaProcessing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CaptchaProcessing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessCaptcha(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CaptchaProcessing/ProcessCaptcha',
            captcha__pb2.CaptchaRequest.SerializeToString,
            captcha__pb2.ResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
